# Generated by Django 5.2.5 on 2025-10-23 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetaAdsCampaign",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("campaign_id", models.CharField(max_length=255)),
                ("campaign_name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("draft", "Draft"),
                        ],
                        default="draft",
                        max_length=50,
                    ),
                ),
                ("budget", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "spend",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("impressions", models.BigIntegerField(default=0)),
                ("clicks", models.BigIntegerField(default=0)),
                ("conversions", models.IntegerField(default=0)),
                (
                    "revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "roi",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "package",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.travelpackage",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WhatsAppConversation",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("conversation_id", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=50)),
                ("last_message_at", models.DateTimeField()),
                ("message_count", models.IntegerField(default=0)),
                (
                    "sentiment_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                (
                    "sentiment_label",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("intent", models.CharField(blank=True, max_length=100, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.customer",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.lead",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Integration",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "integration_type",
                    models.CharField(
                        choices=[
                            ("whatsapp", "WhatsApp Agent"),
                            ("meta_ads", "Meta Ads Agent"),
                            ("salesforce", "Salesforce"),
                            ("stripe", "Stripe"),
                            ("sendgrid", "SendGrid"),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("credentials", models.JSONField()),
                ("settings", models.JSONField(blank=True, null=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integrations",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "unique_together": {("tenant", "integration_type")},
            },
        ),
    ]
